import { BB24_CONFIG, BB24_HOUSEGUESTS } from './data/bb24-config.js';
import { createGameState, activePlayers, addEvent } from './engine/game-state.js';
import { setRelationship, getRelationship, deleteRelationship, areAllied } from './engine/relationships.js';
import { BB24_COMPETITIONS } from './engine/competitions.js';
import * as Engine from './engine/season-engine.js';
import { generateFeedEvent } from './engine/live-feeds.js';

const STORAGE_KEY='bb24-simulator-modular-v1';
let state=createGameState(BB24_CONFIG, BB24_HOUSEGUESTS);
window.BB24_STATE=state;
window.BB24_CONFIG=BB24_CONFIG;

const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const playerName=p=>p?.nickname||p?.firstName||'Unknown';
const image=p=>p?.imageUrl?`<img src="${esc(p.imageUrl)}" alt="${esc(playerName(p))}">`:`<div class="portrait-placeholder">${esc((playerName(p)[0]||'?').toUpperCase())}</div>`;

window.showSection=id=>{document.querySelectorAll('.page-section').forEach(s=>s.classList.toggle('active-section',s.id===id));};
window.selectSeasonTemplate=()=>{ renderAll(); $('selectedSeasonInfo').innerHTML=`<strong>${BB24_CONFIG.name}</strong> — ${BB24_CONFIG.startingPlayers} Houseguests, ${BB24_CONFIG.jurySize}-person jury, Festie Besties, Split House Double Eviction.`; };
window.startNewSeason=()=>{ state=createGameState(BB24_CONFIG, BB24_HOUSEGUESTS); state.started=true; Engine.startSeason(state); window.BB24_STATE=state; saveGame(true); renderAll(); showSection('game'); };
window.saveGame=(silent=false)=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); if(!silent)addEvent(state,'Season saved.'); renderAll();};
window.loadGame=()=>{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;state=JSON.parse(raw);window.BB24_STATE=state;renderAll();};
window.resetGame=()=>{localStorage.removeItem(STORAGE_KEY);state=createGameState(BB24_CONFIG,BB24_HOUSEGUESTS);window.BB24_STATE=state;renderAll();};
window.updateStatValue=id=>{const el=$(id),out=$(id+'Value');if(out)out.textContent=el.value;};
window.cancelHouseguestEdit=()=>{['editingHouseguestId','firstName','lastName','nickname','imageUrl'].forEach(id=>{if($(id))$(id).value='';});$('saveHouseguestButton').textContent='ADD HOUSEGUEST';$('cancelEditButton').classList.add('hidden');};
window.saveHouseguest=()=>{const id=$('editingHouseguestId').value; const data={firstName:$('firstName').value.trim(),lastName:$('lastName').value.trim(),nickname:$('nickname').value.trim()||$('firstName').value.trim(),imageUrl:$('imageUrl').value.trim(),status:'Active',stats:{physical:+$('physical').value,mental:+$('mental').value,social:+$('social').value,strategy:+$('strategy').value}}; if(!data.firstName)return; if(id){Object.assign(state.houseguests.find(p=>p.id===id),data);}else{data.id='custom-'+Date.now();state.houseguests.push(data);} window.cancelHouseguestEdit();renderAll();};
window.createTwist=()=>{const name=$('twistName').value.trim(),description=$('twistDescription').value.trim();if(!name)return;state.twists.push({id:'custom-'+Date.now(),name,description,active:true,weeks:[]});$('twistName').value='';$('twistDescription').value='';renderAll();};
window.createAlliance=()=>{const members=[...$('allianceMembers').selectedOptions].map(o=>o.value);if(!$('allianceName').value.trim()||members.length<2)return;state.alliances.push({id:'a-'+Date.now(),name:$('allianceName').value.trim(),members,strength:$('allianceStrength').value});$('allianceName').value='';renderAll();};
window.saveRelationship=()=>{const from=$('relationshipFrom').value,to=$('relationshipTo').value;if(!from||!to||from===to)return;setRelationship(state,from,to,$('relationshipType').value,$('relationshipNote').value.trim());renderAll();};
window.loadSelectedRelationship=()=>{const r=getRelationship(state,$('relationshipFrom').value,$('relationshipTo').value);$('relationshipType').value=r.type;$('relationshipNote').value=r.note||'';};
window.deleteSelectedRelationship=()=>{deleteRelationship(state,$('relationshipFrom').value,$('relationshipTo').value);renderAll();};
window.proceedGame=()=>{if(!state.started)Engine.startSeason(state); const stage=state.currentStage; if(stage==='hoh')Engine.runHOH(state); else if(stage==='nominations')Engine.runNominations(state); else if(stage==='povPlayers')Engine.selectPOVPlayers(state); else if(stage==='pov')Engine.runPOV(state); else if(stage==='vetoCeremony')Engine.runVetoCeremony(state); else if(stage==='evictionVoting')Engine.runEviction(state); else if(stage==='nextWeek')Engine.advanceWeek(state); else if(stage==='finalHOH1')Engine.runFinalHOHPart(state,1); else if(stage==='finalHOH2')Engine.runFinalHOHPart(state,2); else if(stage==='finalHOH3')Engine.runFinalHOHPart(state,3); else if(stage==='finalEviction')Engine.runFinalEviction(state); else if(stage==='juryVote')Engine.runJuryVote(state); saveGame(true);renderAll();};
window.skipToEnd=()=>{let guard=0;while(!state.finished&&guard++<200){window.proceedGame();}showSection('finale');renderAll();};

function renderCast(){ $('castCount').textContent=state.houseguests.length; $('castGrid').innerHTML=state.houseguests.map(p=>`<div class="cast-card"><div class="cast-photo">${image(p)}</div><h3>${esc(playerName(p))}</h3><p>${esc(p.firstName)} ${esc(p.lastName)}</p><button class="secondary-button" onclick="editPlayer('${p.id}')">EDIT</button></div>`).join(''); }
window.editPlayer=id=>{const p=state.houseguests.find(x=>x.id===id);if(!p)return;$('editingHouseguestId').value=p.id;$('firstName').value=p.firstName;$('lastName').value=p.lastName;$('nickname').value=p.nickname;$('imageUrl').value=p.imageUrl||'';['physical','mental','social','strategy'].forEach(k=>{$(k).value=p.stats?.[k]||5;window.updateStatValue(k);});$('saveHouseguestButton').textContent='SAVE HOUSEGUEST';$('cancelEditButton').classList.remove('hidden');showSection('cast');};
function renderTwists(){const active=state.twists.filter(t=>t.active);$('bbTwistStatusPanel').innerHTML='<h2>Active Season Twists</h2><div class="bb-active-twist-grid">'+active.map(t=>`<div class="bb-active-twist active"><strong>${esc(t.name)}</strong><span>${esc(t.description)}</span></div>`).join('')+'</div>';$('twistList').innerHTML=state.twists.map(t=>`<div class="twist-card"><h3>${esc(t.name)}</h3><p>${esc(t.description)}</p></div>`).join('');}
function renderHouse(){const opts=state.houseguests.map(p=>`<option value="${p.id}">${esc(playerName(p))}</option>`).join('');['allianceMembers','relationshipFrom','relationshipTo'].forEach(id=>{if($(id))$(id).innerHTML=opts;});$('allianceList').innerHTML=state.alliances.map(a=>`<div class="alliance-card"><h3>${esc(a.name)}</h3><p>${a.members.map(id=>playerName(state.houseguests.find(p=>p.id===id))).join(', ')}</p><small>${esc(a.strength)}</small></div>`).join('');$('relationshipsList').innerHTML=Object.values(state.relationships).map(r=>{const a=state.houseguests.find(p=>p.id===r.from),b=state.houseguests.find(p=>p.id===r.to);return `<div class="relationship-card"><strong>${esc(playerName(a))} → ${esc(playerName(b))}</strong><span>${esc(r.type)}</span><small>${esc(r.note||'')}</small></div>`}).join('');}
function renderGame(){const wd=BB24_CONFIG.weeks[String(state.currentWeek)]||{};$('weekBadge').textContent=`WEEK ${state.currentWeek}`;$('weekTitle').textContent=`Week ${state.currentWeek}`;$('stageTitle').textContent=state.currentStage;$('stageName').textContent=state.currentStage;$('stageDescription').textContent=wd.notes||`BB24 — ${wd.format||'normal'} format.`;$('hohStatus').innerHTML=state.currentHOH?inlinePlayer(state.currentHOH):'<span class="status-none">None</span>';$('nomineesStatus').innerHTML=state.nominees.length?state.nominees.map(inlinePlayer).join(''):'<span class="status-none">None</span>';$('povStatus').innerHTML=state.povWinner?inlinePlayer(state.povWinner):'<span class="status-none">None</span>';$('formatStatus').textContent=wd.format||'Normal Week';$('gameHouseguests').innerHTML=state.houseguests.map(p=>`<div class="game-houseguest-card ${p.status!=='Active'?'evicted':''}">${image(p)}<strong>${esc(playerName(p))}</strong><span>${esc(p.status)}</span></div>`).join('');$('eventLog').innerHTML=state.eventLog.map(e=>`<div class="event-entry"><span>${esc(e.time)}</span><p>${esc(e.text)}</p></div>`).join('');}
function inlinePlayer(p){return `<span class="status-person-inline">${p.imageUrl?`<img class="status-player-image" src="${esc(p.imageUrl)}">`:''}<span>${esc(playerName(p))}</span></span>`;}
function renderMemory(){const order=[...state.houseguests];$('memoryWall').innerHTML=order.map(p=>`<div class="memory-wall-card ${p.status!=='Active'?'evicted':''}">${image(p)}<strong>${esc(playerName(p))}</strong><span>${esc(p.status)}</span></div>`).join('');}
function renderJury(){ $('juryList').innerHTML=state.jury.map(p=>`<div class="jury-card">${image(p)}<strong>${esc(playerName(p))}</strong></div>`).join('');$('evictedPlayers').innerHTML=state.evictedHouseguests.map(p=>`<div class="jury-card">${image(p)}<strong>${esc(playerName(p))}</strong></div>`).join(''); }
function renderFinale(){const finalists=activePlayers(state);$('finaleContent').innerHTML=`<div class="panel"><h2>${state.finished?'Season Results':'Finale'}</h2><div class="finale-memory-wall">${[...state.houseguests].sort((a,b)=>(b.status==='Active')-(a.status==='Active')).map((p,i)=>`<div class="finale-player ${p.status!=='Active'?'evicted':''}">${image(p)}<strong>${esc(playerName(p))}</strong><span>${state.finished?(p.id===state.finaleWinner?.id?'1st':finalists.includes(p)?'2nd/3rd':`${state.evictedHouseguests.indexOf(p)+1}th`):p.status}</span></div>`).join('')}</div><div class="final-stage-card"><h3>Final HOH</h3><p>Part 1: ${esc(playerName(state.finalHOH.part1)||'Not played')}</p><p>Part 2: ${esc(playerName(state.finalHOH.part2)||'Not played')}</p><p>Part 3: ${esc(playerName(state.finalHOH.part3)||'Not played')}</p><p>Winner: ${esc(playerName(state.finalHOH.winner)||'Not determined')}</p></div></div>`;}
function renderSummary(){ $('seasonSummary').innerHTML=`<div><strong>Season</strong><span>Big Brother 24</span></div><div><strong>Houseguests</strong><span>${state.houseguests.length}</span></div><div><strong>Active</strong><span>${activePlayers(state).length}</span></div><div><strong>Jury</strong><span>${state.jury.length}/${BB24_CONFIG.jurySize}</span></div>`;}
function renderAll(){renderSummary();renderCast();renderTwists();renderHouse();renderGame();renderMemory();renderJury();renderFinale();$('selectedSeasonInfo').innerHTML=`<strong>${BB24_CONFIG.name}</strong> — ${BB24_CONFIG.startingPlayers} Houseguests · ${BB24_CONFIG.jurySize}-person jury`;}
setInterval(()=>{if(state.started&&!state.finished&&Math.random()<0.35){generateFeedEvent(state);renderGame();}},15000);
selectSeasonTemplate();renderAll();
